project:
  title: "csd-roa-template"

fig-dpi: 300
fig-cap-location: bottom
tbl-cap-location: top

execute:
  echo: false
  warning: false

params:
  logo: logos/nist-logo.png
  roa-number: 646.03-26-XXX
  department: U.S. Department of Commerce
  agency:
    full: National Institute of Standards and Technology
    short: NIST
  laboratory: Material Measurement Laboratory
  division: Chemical Sciences Division
  location: Gaithersburg, MD 20899