project:
  type: csd-roa
format: csd-roa-typst
functions:
  - align
  - text
  - titlecase
  - make-units
  - make-refs
bibliography: refs.bib
fig-dpi: 300
fig-cap-location: bottom
tbl-cap-location: top
execute:
  echo: false
  warning: false
