[[repos]]
repo = "builtin"
hooks = [
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "check-merge-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/jolars/panache-pre-commit"
rev = "v2.51.0"
hooks = [{ id = "panache-lint" }, { id = "panache-format" }]

[[repos]]
repo = "https://github.com/google/yamlfmt"
rev = "v0.21.0"
hooks = [{ id = "yamlfmt" }]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "v1.1.1"
hooks = [{ id = "tombi-format" }]
